### PR TITLE
Fix some heading level issues

### PR DESCRIPTION
**Pull request by tsegismont**
The section did not appear correctly in the TOC.

Also, reordered the clustering subsection

### CODE REVIEW

**Comment by tsegismont** [comment]
Can you please review? Thanks!

**Review by sangeetaraghu — APPROVED** [review]

**Comment by sangeetaraghu** [comment]
@tsegismont Looks good

**Comment by sangeetaraghu** [comment]
@tsegismont We need similar formatting change in all files under community_features
Would you be able to do it in this PR?

**Comment by tsegismont** [comment]
Sure!

**Comment by tsegismont** [comment]
@sangeetaraghu done

**Review by sangeetaraghu — APPROVED** [review]

**Comment by sangeetaraghu** [comment]
@tsegismont Changes look good :). Thank you so much for formatting all the files

**Pull request merged**
